config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'

  get :set_campi, to: 'site#set_campi', path: :campi

  namespace :schedule, path: 'horarios' do
    match :courses, to: 'course#index', via: [:get, :post], path: :cursos
    get :course, to: 'course#show', path: :curso
    match :laboratories, to: 'laboratory#index', via: [:get, :post], path: :laboratorios
    get :laboratory, to: 'laboratory#show', path: :laboratorio
    match :schoolrooms, to: 'schoolroom#index', via: [:get, :post], path: :salas
    get :schoolroom, to: 'schoolroom#show', path: :sala
    match :teachers, to: 'teacher#index', via: [:get, :post], path: :professores
    get :teacher, to: 'teacher#show', path: :professor

  end


  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  if ENV['RAILS_ENV'] == 'test'
    post  :mock_login, to: 'sessions#mock_login'
  end

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters,:except => :show, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'
    resources :reservations,only: [:index,:new,:create] ,path: 'reservas'
    resources :classrooms, path:'turmas' do
      resources :lessons,  path: 'aulas'
    end

    resources :user do
      resources :permission
    end

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
      get :courses, to: 'courses#index'
    end

    resources :courses do
      post 'importar', to: 'courses#import', on: :collection
      get :course_subject, to: 'course_subject#index', path: 'disciplinas'
      get :classrooms, to: 'classrooms#index', path: 'turmas'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
      post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
      post 'importar', to: 'teacher#import', on: :collection
    end

    scope :relatorios do
      get '/', to: 'reports#index', as: 'reports'
      get '/professores',  to: 'reports#professores', as: 'reports_teachers'
      get '/professor/:id',  to: 'reports#professor', as: 'report_teacher'
      get '/salas',  to: 'reports#salas', as: 'reports_schoolrooms'
      get '/sala/:id',  to: 'reports#sala', as: 'report_schoolroom'
      get '/laboratorios',  to: 'reports#laboratorios', as: 'reports_laboratories'
      get '/laboratorio/:id',  to: 'reports#laboratorio', as: 'report_laboratory'
    end
  end
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  validates :maximum_capacity, :amount_resources, :name, :initials, presence: true
  validates :maximum_capacity, :numericality => { :greater_than_or_equal_to => 0 }
  validates :amount_resources, :numericality => { :greater_than_or_equal_to => 0 }
  validate :exist_other_with_this_initials
  validate :exist_other_with_this_name
  has_many :lessons
  has_many :reservation
  belongs_to :campus

  def to_s
    if (self.name == nil)
        "  -  "
    else  "#{self.name}"
    end
  end

  def exist_other_with_this_initials
    @laboratories = Laboratory.all
    unless initials.nil?
    @laboratories.each { |l|
      unless l.id == id
        errors.add(:initials, 'Outro laboratório já possui sigla informada') if l.initials.casecmp(initials) == 0
      end
    }
    end
  end

  def exist_other_with_this_name
    @laboratories = Laboratory.all
    unless name.nil?
    @laboratories.each { |l|
      unless l.id == id
        errors.add(:initials, 'Outro laboratório já possui nome informada') if l.name.casecmp(name) == 0
      end
    }
    end
  end
end

app/controllers/admin/laboratories_controller.rb
class Admin::LaboratoriesController < Admin::AdminController
  include Admin::ImportHelper
  before_action :set_lab, only: [:show, :edit, :update, :destroy]
  before_action :set_authorization, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  def index
    authorize Laboratory
    @laboratories = Laboratory.all.paginate :page => params[:page], :per_page => 10
  end

  def new
    @laboratory = Laboratory.new
  end

  def create
    authorize Laboratory
    @laboratory = Laboratory.new(laboratory_params)
    respond_to do |format|
      if @laboratory.save
        format.html { redirect_to admin_laboratories_path, notice: 'Laboratorio cadastrado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @laboratory.update(laboratory_params)
        format.html { redirect_to admin_laboratories_path, notice: 'Laboratorio atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @laboratory.destroy
    redirect_to admin_laboratories_path
  end

  private
    def set_lab
      @laboratory = Laboratory.find(params[:id])
    end

    def set_authorization
      authorize Laboratory
    end

    def laboratory_params
      params.require(:laboratory).permit(:maximum_capacity, :amount_resources, :status, :name, :initials, :campus_id)
    end
end

app/controllers/schedule/laboratory_controller.rb
class Schedule::LaboratoryController < SiteController
  def index
    @labs = Laboratory.where(campus: get_campi)
  end

  def show
    @lessons = Lesson.by_laboratory(params[:lab])
    @schedules = CampusSchedule.where(campus: get_campi).order(:shift)
  end
end

app/helpers/admin/laboratories_helper.rb
module Admin::LaboratoriesHelper
end

app/views/admin/laboratories/edit.html.erb
<%= render 'admin/partials/error_messages', resource: @laboratory, field: true %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="form-horizontal">
        <div class="panel-heading"><svg class="glyph stroked desktop computer and mobile"><use xlink:href="#stroked-desktop-computer-and-mobile"></use></svg> Editar laboratório</div>
        <div class="panel-body">
          <div class="col-md-12">
            <%= form_for @laboratory, url: admin_laboratory_path, method: :patch do |f| %>
            <div class="form-group ">
              <%= f.label :name, "Nome", class: "col-sm-2 control-label"%>
              <div class="col-sm-4">
                <%= f.text_field :name , class:"form-control"%>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :initials,"Sigla", class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.text_field :initials, class:"form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :maximum_capacity, "Capacidade máxima",class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.number_field :maximum_capacity, class:"form-control" %>
              </div>
            </div>
            <div class="form-group ">
              <%= f.label :amount_resources, "Quantidade de recursos", class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.number_field :amount_resources, class:"form-control"  %>
              </div>
            </div>

            <div class="form-group ">
              <%= f.label :campus, class: "col-sm-2 control-label" %>
              <div class="col-sm-2">

                <%= f.select("campus_id", Campus.all.collect { |c| [c.description, c.id]}, {}, class: "selectpicker", data: {width: "auto"}) %>
              </div>
            </div>

            <div class="form-group ">
              <%= f.label :status, class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.select :status, [['Ativo', true], ['Inativo', false]], {}, class: "selectpicker", data: {width: "auto"}  %>
              </div>

            </div>

            <div class="row">
              <div class="col-md-5">

              </div>
              <div class="col-md-7">
                <%= f.submit 'Salvar', class: 'btn btn-success' %>
              </div>
            </div>

            <% end %>
          </div><!-- panel-body -->
        </div><!-- panel panel-default -->
      </div>
    </div>

app/views/admin/laboratories/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Laboratórios
          </div>
          <div class="col-md-4">
            <%= link_to('Novo Laboratório', new_admin_laboratory_path, class: "btn btn-success pull-right")%>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import" data-search="true">
          <thead>
            <th>Id</th>
            <th>Nome</th>
            <th>Sigla</th>
            <th>Ações</th>
            <th></th>
            <th></th>
          </thead>

          <tbody>
            <% @laboratories.each do |laboratory| %>
            <tr>
              <td><%= laboratory.id %></td>
              <td><%= laboratory.name %></td>
              <td><%= laboratory.initials %></td>
              <td style="text-align:center">
                <%= link_to admin_laboratory_path(laboratory), class: "label label-info" do %>
                <span>Detalhes</span>
                <% end %>
              </td>
              <td style="text-align:center">
                <%= link_to edit_admin_laboratory_path(laboratory), class: "label label-primary" do %>
                <span>Editar</span>
                <% end %>
              </td>
              <td style="text-align:center">
                <%= link_to admin_laboratory_path(laboratory),
                method: :delete,
                data: { confirm: 'Tem certeza que quer apagar laboratório?' },
                class: "label label-danger" do %>
                <span>Excluir</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <nav>
        <ul class="pager">
           <%= page_entries_info @laboratories %>
           <br>
          <li><%= will_paginate @laboratories, :page_links => false, :container => false %></li>
        </ul>
      </nav>
      </div>
    </div>
  </div>
</div>

app/views/admin/laboratories/new.html.erb
<%= render 'admin/partials/error_messages', resource: @laboratory, field: true %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="form-horizontal">
        <div class="panel-heading"><svg class="glyph stroked desktop computer and mobile"><use xlink:href="#stroked-desktop-computer-and-mobile"></use></svg> Novo laboratório</div>
        <div class="panel-body">
          <div class="col-md-12">
            <%= form_for :laboratory, url: admin_laboratories_path do |f| %>

            <div class="form-group ">
              <%= f.label :name, "Nome", class: "col-sm-2 control-label"%>
              <div class="col-sm-4">
                <%= f.text_field :name , class:"form-control"%>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :initials,"Sigla", class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.text_field :initials, class:"form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :maximum_capacity, "Capacidade máxima",class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.number_field :maximum_capacity, class:"form-control" %>
              </div>
            </div>
            <div class="form-group ">
              <%= f.label :amount_resources, "Quantidade de recursos", class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.number_field :amount_resources, class:"form-control"  %>
              </div>
            </div>

            <div class="form-group ">
              <%= f.label :campus, class: "col-sm-2 control-label" %>
              <div class="col-sm-2">

                <%= f.select("campus_id", Campus.all.collect { |c| [c.description, c.id]}, {}, class: "selectpicker", data: {width: "auto"}) %>
              </div>
            </div>

            <div class="form-group ">
              <%= f.label :status, class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.select :status, [['Ativo', true], ['Inativo', false]],  class:"form-control"  %>
              </div>

            </div>

            <div class="row">
              <div class="col-md-5">

              </div>
              <div class="col-md-7">
                <%= f.submit 'Salvar', class: 'btn btn-success' %>
              </div>
            </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/admin/laboratories/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default ">
      <div class="form-horizontal">
        <div class="panel-heading"><svg class="glyph stroked desktop computer and mobile"><use xlink:href="#stroked-desktop-computer-and-mobile"></use></svg> Laboratório <%= @laboratory.initials%></div>
          <div class="panel-body">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-4">
                  <%= label_tag("Nome: ")%>
                  <%= @laboratory.name%>
                </div>
                </div>
                <br />
                <div class="row">
                  <div class="col-md-4">
                    <%= label_tag("Sigla: ")%>
                    <%= @laboratory.initials %>
                  </div>
                </div>
              <br />
              <div class="row ">
                <div class="col-md-4">
                  <%= label_tag("Capacidade máxima: ")%>
                  <%= @laboratory.maximum_capacity %>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-4">
                  <%= label_tag("Quantidade de recursos: ")%>
                  <%= @laboratory.amount_resources %>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-4">
                  <%= label_tag("Campus: ")%>
                  <%= @laboratory.campus.description %>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-3">
                  <%= label_tag("Status: ")%>
                  <% if @laboratory.status? %>
                  <span class="label label-success">Ativo</span>
                  <% else %>
                  <span class="label label-danger">Inativo</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>