config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'

  get :set_campi, to: 'site#set_campi', path: :campi

  namespace :schedule, path: 'horarios' do
    match :courses, to: 'course#index', via: [:get, :post], path: :cursos
    get :course, to: 'course#show', path: :curso
    match :laboratories, to: 'laboratory#index', via: [:get, :post], path: :laboratorios
    get :laboratory, to: 'laboratory#show', path: :laboratorio
    match :schoolrooms, to: 'schoolroom#index', via: [:get, :post], path: :salas
    get :schoolroom, to: 'schoolroom#show', path: :sala
    match :teachers, to: 'teacher#index', via: [:get, :post], path: :professores
    get :teacher, to: 'teacher#show', path: :professor

  end


  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  if ENV['RAILS_ENV'] == 'test'
    post  :mock_login, to: 'sessions#mock_login'
  end

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters,:except => :show, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'
    resources :reservations,only: [:index,:new,:create] ,path: 'reservas'
    resources :classrooms, path:'turmas' do
      resources :lessons,  path: 'aulas'
    end

    resources :user do
      resources :permission
    end

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
      get :courses, to: 'courses#index'
    end

    resources :courses do
      post 'importar', to: 'courses#import', on: :collection
      get :course_subject, to: 'course_subject#index', path: 'disciplinas'
      get :classrooms, to: 'classrooms#index', path: 'turmas'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
      post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
      post 'importar', to: 'teacher#import', on: :collection
    end

    scope :relatorios do
      get '/', to: 'reports#index', as: 'reports'
      get '/professores',  to: 'reports#professores', as: 'reports_teachers'
      get '/professor/:id',  to: 'reports#professor', as: 'report_teacher'
      get '/salas',  to: 'reports#salas', as: 'reports_schoolrooms'
      get '/sala/:id',  to: 'reports#sala', as: 'report_schoolroom'
      get '/laboratorios',  to: 'reports#laboratorios', as: 'reports_laboratories'
      get '/laboratorio/:id',  to: 'reports#laboratorio', as: 'report_laboratory'
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController
  before_action :set_days, only: [:professor, :sala, :laboratorio]
    
  def index

  end

  def professores
    @teachers = Teacher.all
  end

  def salas
    @schoolrooms = Schoolroom.all
  end

  def laboratorios
    @laboratories = Laboratory.all
  end

  def professor
    @teacher = Teacher.find(params[:id])
    @classrooms = Classroom.where(teacher: @teacher)
    @lessons = Lesson.where(classroom: @classrooms)
    @campus = []
    @lessons.each do |l|
      @campus << l.laboratory.campus if not l.laboratory.nil?
      @campus << l.schoolroom.campus if not l.schoolroom.nil?
    end
    @campus = @campus.uniq
    @schedules = CampusSchedule.where(campus: @campus.first)
  end

  def sala
    @schoolroom = Schoolroom.find(params[:id])
    @lessons = Lesson.where(schoolroom: @schoolroom)
    @campus = @schoolroom.campus
  end

  def laboratorio
    @laboratory = Laboratory.find(params[:id])
    @lessons = Lesson.where(laboratory: @laboratory)
    @campus = @laboratory.campus
  end

  def set_days
    @days = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta']  
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_calendar.html.erb
<div class="diary-book campus-<%= campi.id %>">
  <div class="content">
    <div class="days">
      <div class="day -Horario">Horário</div>
      <div class="day -Segunda">Segunda</div>
      <div class="day -Terca">Terça</div>
      <div class="day -Quarta">Quarta</div>
      <div class="day -Quinta">Quinta</div>
      <div class="day -Sexta">Sexta</div>
    </div>

    <div class="courses">
      <% CampusSchedule.where(campus: campi).each do |cs| %>
        <div class="hour">
          <%= cs.start.strftime("%H:%M")%> - <%= cs.end.strftime("%H:%M") %>
        </div>
        <% days.each_with_index do |day, i| %>
          <% if not lessons.find_by(campus_schedule: cs, day: day).nil? %>
            <div class="course <%= I18n.transliterate(lessons.find_by(campus_schedule: cs, day: day).day) %>">
              <%= lessons.find_by(campus_schedule: cs, day: day) %>
            </div>
            <% else %>
              <div class="course <%= I18n.transliterate(day) %>"></div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/reports/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            <svg class="glyph stroked clipboard with paper"><use xlink:href="#stroked-clipboard-with-paper"/></svg>
            Relatórios
          </div>
        </div>
      </div> <!-- panel-heading -->

      <div class="panel-body">
        <div class="row">
          <div class="col-md-3">Cursos</div>
          <div class="col-md-9">
            <a class="btn btn-default" href="#">
              <span>Visualizar</span>
            </a>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3">Salas</div>
          <div class="col-md-9">
            <%= link_to admin_reports_schoolrooms_path, class: "btn btn-default" do %>
              <span>Visualizar</span>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3">Laboratórios</div>
          <div class="col-md-9">
            <%= link_to admin_reports_laboratories_path, class: "btn btn-default" do %>
              <span>Visualizar</span>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3">Professores</div>
          <div class="col-md-9">
            <%= link_to admin_reports_teachers_path, class: "btn btn-default" do %>
              <span>Visualizar</span>
            <% end %>
          </div>
        </div>
      </div> <!-- panel-body -->

    </div>
  </div>
</div>

app/views/admin/reports/laboratorio.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked notepad "><use xlink:href="#stroked-notepad"/></svg> Aulas
          </div>
          <div class="col-md-4"></div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'calendar', days: @days, lessons: @lessons, campi: @campus %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/laboratorios.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Laboratórios
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import" data-search="true" data-pagination="true">
          <thead>
            <th>Id</th>
            <th>Nome</th>
            <th>Sigla</th>
            <th>Ações</th>
          </thead>

          <tbody>
            <% @laboratories.each do |laboratory| %>
            <tr>
              <td><%= laboratory.id %></td>
              <td><%= laboratory.name %></td>
              <td><%= laboratory.initials %></td>
              <td style="text-align:center">
                <%= link_to admin_report_laboratory_path(laboratory), class: "btn btn-default" do %>
                <span>Ver horarios</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/professor.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= form_tag(importar_admin_course_subject_index_path, class: 'form-inline') do |f| %>
        <div class="row">
          <div class="col-md-8">
            <%= label_tag("id_campus", "Campus") %>
            <%= select_tag("id_campus", options_from_collection_for_select(@campus, 'id', 'description'), id: "campus", class: "selectpicker", include_blank: 'Select Campus', data: {width: "50%"}) %>
          </div>
        </div>
        <% end %>
      </div>

      <div class="panel-body">
        <% @campus.each do |c, i| %>
        <%= render 'calendar', days: @days, lessons: @lessons, campi: c %>
        <% end %>
      </div>
    </div>

    <script>
      $(".diary-book").hide();
      $("#campus").change(function() {
        var selopt = $(this.children[this.selectedIndex]),
        val = selopt.attr('value');
        if(val != null) {
          var str = ".diary-book.campus-".concat(val);
          $(".diary-book").hide();
          $(str).show();
        }
      })
    </script>
  </div>
</div>

app/views/admin/reports/professores.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Laboratórios
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import" data-search="true" data-pagination="true">
          <thead>
            <th>Matricula</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Campus</th>
            <th>Departamento</th>
            <th>Ações</th>
          </thead>

          <tbody>
            <% @teachers.each do |teacher| %>
            <tr>
              <td><%= teacher.id %></td>
              <td><%= teacher.name %></td>
              <td><%= teacher.mail %></td>
              <td><%= teacher.campus %></td>
              <td><%= teacher.department %></td>
              <td style="text-align:center">
                <%= link_to admin_report_teacher_path(teacher), class: "btn btn-default" do %>
                <span>Ver horarios</span>
                <% end %>
              </td>
            </tr>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/sala.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked notepad "><use xlink:href="#stroked-notepad"/></svg> Aulas
          </div>
          <div class="col-md-4"></div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'calendar', days: @days, lessons: @lessons, campi: @campus %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/salas.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Salas
          </div>
          <div class="col-md-4">

          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import" data-search="true" data-pagination="true">
          <thead>
            <th>Id</th>
            <th>Nome</th>
            <th>Sigla</th>
            <th>Ações</th>
          </thead>

          <tbody>
            <% @schoolrooms.each do |schoolroom| %>
            <tr>
              <td><%= schoolroom.id %></td>
              <td><%= schoolroom.name %></td>
              <td><%= schoolroom.initials %></td>
              <td style="text-align:center">
                <%= link_to admin_report_schoolroom_path(schoolroom), class: "btn btn-default" do %>
                <span>Ver horarios</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>