config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'

  get :set_campi, to: 'site#set_campi', path: :campi

  namespace :schedule, path: 'horarios' do
    match :courses, to: 'course#index', via: [:get, :post], path: :cursos
    get :course, to: 'course#show', path: :curso
    match :laboratories, to: 'laboratory#index', via: [:get, :post], path: :laboratorios
    get :laboratory, to: 'laboratory#show', path: :laboratorio
    match :schoolrooms, to: 'schoolroom#index', via: [:get, :post], path: :salas
    get :schoolroom, to: 'schoolroom#show', path: :sala
    match :teachers, to: 'teacher#index', via: [:get, :post], path: :professores
    get :teacher, to: 'teacher#show', path: :professor

  end


  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  if ENV['RAILS_ENV'] == 'test'
    post  :mock_login, to: 'sessions#mock_login'
  end

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters,:except => :show, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'
    resources :reservations,only: [:index,:new,:create] ,path: 'reservas'
    resources :classrooms, path:'turmas' do
      resources :lessons,  path: 'aulas'
    end

    resources :user do
      resources :permission
    end

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
      get :courses, to: 'courses#index'
    end

    resources :courses do
      post 'importar', to: 'courses#import', on: :collection
      get :course_subject, to: 'course_subject#index', path: 'disciplinas'
      get :classrooms, to: 'classrooms#index', path: 'turmas'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
      post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
      post 'importar', to: 'teacher#import', on: :collection
    end

    scope :relatorios do
      get '/', to: 'reports#index', as: 'reports'
      get '/professores',  to: 'reports#professores', as: 'reports_teachers'
      get '/professor/:id',  to: 'reports#professor', as: 'report_teacher'
      get '/salas',  to: 'reports#salas', as: 'reports_schoolrooms'
      get '/sala/:id',  to: 'reports#sala', as: 'report_schoolroom'
      get '/laboratorios',  to: 'reports#laboratorios', as: 'reports_laboratories'
      get '/laboratorio/:id',  to: 'reports#laboratorio', as: 'report_laboratory'
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_action :set_semester, :set_days, :set_campus

  def index
  end

  def set_campi
    session[:campus_id] = params[:campus]
    redirect_to params[:next] || root_path
  end

  private
  def get_campi
    session[:campus_id] || 3
  end

  def set_campus
    @campus = Campus.all
  end

  def set_semester
    @current_semester = Semester.where(status: true).last
  end

  def set_days
    @days = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta']
  end
end

app/helpers/site_helper.rb
module SiteHelper
  def format_lesson_info(lesson)
    if lesson.schoolroom and lesson.laboratory
      "#{lesson.classroom.name} <br> #{lesson.schoolroom.name} <br> #{lesson.laboratory.name}".html_safe
    elsif not lesson.schoolroom and lesson.laboratory
      "#{lesson.classroom.name} <br> #{lesson.laboratory.name} <br> #{lesson.classroom.teacher.name}".html_safe
    elsif lesson.schoolroom and not lesson.laboratory
      "#{lesson.classroom.name} <br> #{lesson.schoolroom.name} <br> #{lesson.classroom.teacher.name}".html_safe
    end
  end

  def get_sigla(campus)
    campus.sigla.split("-")[1] || campus.sigla
  end

  def current_campi
    Campus.find_by(id: session[:campus_id]) || Campus.find_by(id: 3) || Campus.first
  end
end

app/views/site/_calendar.html.erb
<div class="diary-book">
  <div class="content">
    <div class="days">
      <div class="day -Segunda">Segunda</div>
      <div class="day -Terca">Terça</div>
      <div class="day -Quarta">Quarta</div>
      <div class="day -Quinta">Quinta</div>
      <div class="day -Sexta">Sexta</div>
    </div>

    <div class="courses">
      <% schedules.each do |cs| %>
        <% days.each_with_index do |day, i| %>
          <% if not lessons.find_by(campus_schedule: cs, day: day).nil? %>
            <div class="course <%= I18n.transliterate(lessons.find_by(campus_schedule: cs, day: day).day) %>">
              <%= format_lesson_info(lessons.find_by(campus_schedule: cs, day: day)) %>
            </div>
            <% else %>
              <div class="course <%= I18n.transliterate(day) %>"></div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="hours">
    <div class="hour">Horário</div>
    <% schedules.each do |schedule| %>
      <div class="hour">
        <%= schedule.start.strftime("%H:%M")%> - <%=schedule.end.strftime("%H:%M") %>
      </div>
    <% end %>
  </div>
</div>

app/views/site/_menu.html.erb
<div class="actions clearfix">
  <div class="row">
    <div class="col-md-3">
      <%= link_to("Cursos", schedule_courses_path, class: "btn btn-default btn-block btn-lg #{current_page?(schedule_courses_path) ? 'active' : ''}") %>
    </div>
    <div class="col-md-3">
      <%= link_to("Laboratórios", schedule_laboratories_path, class: "btn btn-default btn-block btn-lg #{current_page?(schedule_laboratories_path) ? 'active' : ''}") %>
    </div>
    <div class="col-md-3">
      <%= link_to("Salas", schedule_schoolrooms_path, class: "btn btn-default btn-block btn-lg #{current_page?(schedule_schoolrooms_path) ? 'active' : ''}") %>
    </div>
    <div class="col-md-3">
      <%= link_to("Professores", schedule_teachers_path, class: "btn btn-default btn-block btn-lg #{current_page?(schedule_teachers_path) ? 'active' : ''}") %>
    </div>
  </div>
</div>

app/views/site/index.html.erb
<%= render "menu" %>
<div>
  <%= image_tag "logo.png", class: "img-responsive center-block" %>
</div>