config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'

  get :set_campi, to: 'site#set_campi', path: :campi

  namespace :schedule, path: 'horarios' do
    match :courses, to: 'course#index', via: [:get, :post], path: :cursos
    get :course, to: 'course#show', path: :curso
    match :laboratories, to: 'laboratory#index', via: [:get, :post], path: :laboratorios
    get :laboratory, to: 'laboratory#show', path: :laboratorio
    match :schoolrooms, to: 'schoolroom#index', via: [:get, :post], path: :salas
    get :schoolroom, to: 'schoolroom#show', path: :sala
    match :teachers, to: 'teacher#index', via: [:get, :post], path: :professores
    get :teacher, to: 'teacher#show', path: :professor

  end


  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  if ENV['RAILS_ENV'] == 'test'
    post  :mock_login, to: 'sessions#mock_login'
  end

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters,:except => :show, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'
    resources :reservations,only: [:index,:new,:create] ,path: 'reservas'
    resources :classrooms, path:'turmas' do
      resources :lessons,  path: 'aulas'
    end

    resources :user do
      resources :permission
    end

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
      get :courses, to: 'courses#index'
    end

    resources :courses do
      post 'importar', to: 'courses#import', on: :collection
      get :course_subject, to: 'course_subject#index', path: 'disciplinas'
      get :classrooms, to: 'classrooms#index', path: 'turmas'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
      post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
      post 'importar', to: 'teacher#import', on: :collection
    end

    scope :relatorios do
      get '/', to: 'reports#index', as: 'reports'
      get '/professores',  to: 'reports#professores', as: 'reports_teachers'
      get '/professor/:id',  to: 'reports#professor', as: 'report_teacher'
      get '/salas',  to: 'reports#salas', as: 'reports_schoolrooms'
      get '/sala/:id',  to: 'reports#sala', as: 'report_schoolroom'
      get '/laboratorios',  to: 'reports#laboratorios', as: 'reports_laboratories'
      get '/laboratorio/:id',  to: 'reports#laboratorio', as: 'report_laboratory'
    end
  end
end

app/models/campus.rb
class Campus < ApplicationRecord
  validates :description, :sigla, presence: true

  has_many :courses
  has_many :schoolrooms
  has_many :laboratories
end

app/controllers/admin/campus_controller.rb
class Admin::CampusController < Admin::AdminController

  include Admin::ImportHelper

  def index
    authorize Campus
    @campus = Campus.all.order(id: :asc).paginate :page => params[:page], :per_page => 10
  end

  def import
    authorize Campus
    response = request_suap_api({url: 'https://suap.ifpb.edu.br/edu/api/receber_campus/'})

    response.each do |pk, campi|
      campus = Campus.find_or_create_by(id: pk.to_i)
      campus.description = campi['descricao']
      campus.sigla = campi['sigla']

      campus.save
    end

    flash[:success] = 'Dados importados com sucesso'
    redirect_to action: :index
  end
end

app/helpers/admin/campus_helper.rb
module Admin::CampusHelper
end

app/views/admin/campus/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked home"><use xlink:href="#stroked-home"/></svg>
            Campi
          </div>
          <div class="col-md-4">
            <%= link_to('Importar do SUAP', importar_admin_campus_index_path, class: "btn btn-success pull-right")%>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import">
          <thead>
            <th>Sigla</th>
            <th>Descrição</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <%- @campus.each do |campi| %>
            <tr>
              <td><%= campi.sigla %></td>
              <td><%= campi.description %></td>
              <td>
                <%= link_to('Ver horários', admin_campus_campus_schedules_path(campi), class: 'btn btn-default')%>
                <%= link_to('Ver cursos', admin_campus_courses_path(campi), class: 'btn btn-default')%>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <nav aria-label="...">
        <ul class="pager">
          <%= page_entries_info @campus %>
          <br>
          <li><%= will_paginate @campus, :page_links => false, :container => false %></li>
        </ul>
      </nav>

      </div>
    </div>
  </div>
</div>

app/views/admin/campus/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Campi IFPB</h1>
  </div>
</div><!--/.row-->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to('Importar do SUAP', importar_campus_admin_campus_path, class: "btn btn-success pull-right")%>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <th>#</th>
            <th>Sigla</th>
            <th>Descrição</th>
            <th>Importado em</th>
            <th>Atualizado em</th>
          </thead>

          <tbody>
            <%- @campus.each do |campi| %>
            <tr>
              <td><%= campi.id %></td>
              <td><%= campi.sigla %></td>
              <td><%= campi.description %></td>
              <td><%= campi.created_at %></td>
              <td><%= campi.updated_at %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>